# Pengaturan Monitoring

# int: nilai bilangan bulat
# float: nilai desimal
# bool: true/false
# str: teks/string
# literal: pilihan nilai tertentu, misalnya ["option1", "option2", null]
# optional: tidak wajib diisi, kalau kosong akan pakai nilai default

RETRY_ATTEMPT: 20 # int, opsional
CHECK_INTERVAL: 5 # int (dalam detik) disarankan > 5, opsional
THRESHOLD_KBPS: 1000.0 # float (KB/s), disarankan > 100 KB/s, opsional
DURATION_STABLE: 60 # int (detik), opsional

IO_THRESHOLD_KBPS: 2000.0 # float (KB/s), disarankan > 1000 KB/s, opsional
IO_CHECK_INTERVAL: 5 # int (dalam detik), opsional
IO_RETRY_ATTEMPT: 15 # int, opsional
IO_DURATION_STABLE: 60 # int (detik), opsional

POST_MONITORING: null # Aksi setelah monitoring selesai, pilihan: ["shutdown", "sleep", null], opsional
POST_MONITORING_DELAY: 60 # int (detik), jeda sebelum menjalankan aksi POST_MONITORING, opsional

RINGTONE: true # bool, opsional, apakah mau memutar suara saat monitoring selesai
RINGTONE_LOOP: "loop" # int | literal ["loop"], contoh: 5 atau "loop". opsional, apakah suara diulang sampai dihentikan, RINGTONE harus true
RINGTONE_PATH: null # str, opsional, lokasi file ringtone (format mp3), RINGTONE harus true, default "lib/ringtone.mp3"

# Token bot Telegram kamu dan chat ID tujuan notifikasi

TELEGRAM_DASHBOARD_ENABLED: false # bool, opsional
BOT_LISTENER: false # bool, opsional. Aktifkan agar bot bisa menerima perintah
BOT_TOKEN: "" # str, TELEGRAM_MONITORING_ENABLED wajib true!
CHAT_ID: "" # str, TELEGRAM_MONITORING_ENABLED wajib true!
